# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f68deb94a3fae909fc7ca852e122aeb9203dfa6c959da4c51a4855a72e19200799414501f1dfe25c35a77ea1f552b9c1941edf55772fc6beb959f0d99709d3b3

test:
  secret_key_base: b99b71ccc6b23b2f1ef651585bb5532b2641ad5aa6a082e2c0ec64ed40149609b9aceda0e4eac873e087e05eaf38fbae454fc0a4823df0160a31f50a9164ffdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
